### ISSUE TITLE
Execution should log commit or version of test being run

### ISSUE THREAD

**Issue by ecrist** [OpenVPN/easyrsa-unit-tests#2]
Right now, there's no way to know which version of the test was run, since we're just grabbing the raw file and running it.  We need some output that says something akin to "Running operational tests version 1.3" or "Running operational test commit 0f33aa21" or something.

**Comment by TinCanTech** [comment]
Linux can use `curl` to retrieve the current commit ID
Windows will probably have to fall back to a built in version.

**Comment by TinCanTech** [comment]
Closed via 2255a020f07e982182c2d8829cf9b633c15f9544
